version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"  # Прокидываем порт 80 для доступа к nginx снаружи
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Подключаем конфигурацию nginx
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  frontend:
    container_name: frontend
    build:
      context: ./front
    restart: always
    expose:
      - "80"
    networks:
      - app-network
    depends_on:
      - backend
      - db

  backend:
    container_name: backend
    build:
      context: ./back
    restart: always
    expose:
      - "5000"
    env_file:
      - ./back/.env
    volumes:
      - uploads_data:/back/uploads
    networks:
      - app-network
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:14
    environment:
      POSTGRES_DB: amk
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1122
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  uploads_data:
